---
abstract: 'IPFilter.dat parser'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  CPAN::Meta::Converter: '0'
  CPAN::Meta::Validator: '0'
  Exporter: '0'
  File::Path: '2.07'
  File::Spec: '0'
  File::Temp: '0'
  JSON: '0'
  Module::Build: '0.3'
  Perl::Tidy: '0'
  TAP::Harness: '3.18'
  Test::Class: '0.35'
  Test::Exception: '0'
  Test::Most: '0'
  perl: v5.10.0
configure_requires:
  Module::Build: '0.36'
dynamic_config: 0
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
keywords:
  - BitTorrent
  - eMule
  - IP
  - Filter
  - IPFilter.dat
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-IPFilter
provides:
  Config::IPFilter:
    file: lib/Config/IPFilter.pm
    version: '1.00'
  Config::IPFilter::Rule:
    file: lib/Config/IPFilter/Rule.pm
    version: '1.00'
  Config::IPFilter::Types:
    file: lib/Config/IPFilter/Types.pm
    version: '1.00'
requires:
  Moose: '0'
  perl: v5.10.0
resources:
  ChangeLog: http://github.com/sanko/config-ipfilter/commits/
  homepage: http://sankorobinson.com/config-ipfilter/
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '1.00'
